package com.demo.models;
// Generated Jan 1, 2022, 12:13:20 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "booking_hotel")
public class Account implements java.io.Serializable {

	private String idAcc;
	private String username;
	private String password;
	private String email;
	private String name;
	private String gender;
	private String location;
	private int phone;
	private boolean status;
	private String avatar;
	private Date datecreated;
	private String idRole;
	private Set<InfoRoom> infoRooms = new HashSet<InfoRoom>(0);
	private Set<GuestRating> guestRatings = new HashSet<GuestRating>(0);
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Roles> roleses = new HashSet<Roles>(0);
	

	public Account() {
	}

	public Account(String idAcc, String username, String password, String email, String name, String gender,
			String location, int phone, boolean status, String avatar, Date datecreated, String idRole) {
		this.idAcc = idAcc;
		this.username = username;
		this.password = password;
		this.email = email;
		this.name = name;
		this.gender = gender;
		this.location = location;
		this.phone = phone;
		this.status = status;
		this.avatar = avatar;
		this.datecreated = datecreated;
		this.idRole = idRole;
	}

	public Account(String idAcc, String username, String password, String email, String name, String gender,
			String location, int phone, boolean status, String avatar, Date datecreated, String idRole,
			Set<InfoRoom> infoRooms, Set<GuestRating> guestRatings, Set<Bill> bills, Set<Roles> roleses) {
		this.idAcc = idAcc;
		this.username = username;
		this.password = password;
		this.email = email;
		this.name = name;
		this.gender = gender;
		this.location = location;
		this.phone = phone;
		this.status = status;
		this.avatar = avatar;
		this.datecreated = datecreated;
		this.idRole = idRole;
		this.infoRooms = infoRooms;
		this.guestRatings = guestRatings;
		this.bills = bills;
		this.roleses = roleses;
	}

	@Id

	@Column(name = "id_acc", unique = true, nullable = false, length = 50)
	public String getIdAcc() {
		return this.idAcc;
	}

	public void setIdAcc(String idAcc) {
		this.idAcc = idAcc;
	}

	@Column(name = "username", nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false, length = 200)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "location", nullable = false, length = 250)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "phone", nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "avatar", nullable = false, length = 65535)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecreated", nullable = false, length = 10)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "id_role", nullable = false, length = 50)
	public String getIdRole() {
		return this.idRole;
	}

	public void setIdRole(String idRole) {
		this.idRole = idRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<InfoRoom> getInfoRooms() {
		return this.infoRooms;
	}

	public void setInfoRooms(Set<InfoRoom> infoRooms) {
		this.infoRooms = infoRooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<GuestRating> getGuestRatings() {
		return this.guestRatings;
	}

	public void setGuestRatings(Set<GuestRating> guestRatings) {
		this.guestRatings = guestRatings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "account_role", catalog = "booking_hotel", joinColumns = {
			@JoinColumn(name = "id_acc", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_role", nullable = false, updatable = false) })
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
