package com.demo.models;
// Generated Jan 8, 2022, 5:55:33 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "booking_hotel")
public class Bill implements java.io.Serializable {

	private String idBill;
	private Account account;
	private String accountIdHotel;
	private double totalMoney;
	private Date created;
	private boolean status;
	private Set<DetailBill> detailBills = new HashSet<DetailBill>(0);

	public Bill() {
	}

	public Bill(String idBill, Account account, String accountIdHotel, double totalMoney, Date created,
			boolean status) {
		this.idBill = idBill;
		this.account = account;
		this.accountIdHotel = accountIdHotel;
		this.totalMoney = totalMoney;
		this.created = created;
		this.status = status;
	}

	public Bill(String idBill, Account account, String accountIdHotel, double totalMoney, Date created, boolean status,
			Set<DetailBill> detailBills) {
		this.idBill = idBill;
		this.account = account;
		this.accountIdHotel = accountIdHotel;
		this.totalMoney = totalMoney;
		this.created = created;
		this.status = status;
		this.detailBills = detailBills;
	}

	@Id

	@Column(name = "id_bill", unique = true, nullable = false, length = 250)
	public String getIdBill() {
		return this.idBill;
	}

	public void setIdBill(String idBill) {
		this.idBill = idBill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "account_id_hotel", nullable = false, length = 250)
	public String getAccountIdHotel() {
		return this.accountIdHotel;
	}

	public void setAccountIdHotel(String accountIdHotel) {
		this.accountIdHotel = accountIdHotel;
	}

	@Column(name = "total_money", nullable = false, precision = 22, scale = 0)
	public double getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(double totalMoney) {
		this.totalMoney = totalMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<DetailBill> getDetailBills() {
		return this.detailBills;
	}

	public void setDetailBills(Set<DetailBill> detailBills) {
		this.detailBills = detailBills;
	}

}
