package com.demo.models;
// Generated Jan 13, 2022, 7:32:19 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetailBill generated by hbm2java
 */
@Entity
@Table(name = "detail_bill", catalog = "booking_hotel")
public class DetailBill implements java.io.Serializable {

	private String idBill;
	private Reservation reservation;
	private String payerName;
	private int payerPhone;
	private String payerEmail;
	private String typePay;
	private double discount;
	private double totalMoney;
	private Date created;
	private boolean status;

	public DetailBill() {
	}

	public DetailBill(String idBill, Reservation reservation, String payerName, int payerPhone, String payerEmail,
			String typePay, double discount, double totalMoney, Date created, boolean status) {
		this.idBill = idBill;
		this.reservation = reservation;
		this.payerName = payerName;
		this.payerPhone = payerPhone;
		this.payerEmail = payerEmail;
		this.typePay = typePay;
		this.discount = discount;
		this.totalMoney = totalMoney;
		this.created = created;
		this.status = status;
	}

	@Id

	@Column(name = "id_bill", unique = true, nullable = false, length = 250)
	public String getIdBill() {
		return this.idBill;
	}

	public void setIdBill(String idBill) {
		this.idBill = idBill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reservation_id", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@Column(name = "payer_name", nullable = false, length = 250)
	public String getPayerName() {
		return this.payerName;
	}

	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	@Column(name = "payer_phone", nullable = false)
	public int getPayerPhone() {
		return this.payerPhone;
	}

	public void setPayerPhone(int payerPhone) {
		this.payerPhone = payerPhone;
	}

	@Column(name = "payer_email", nullable = false, length = 250)
	public String getPayerEmail() {
		return this.payerEmail;
	}

	public void setPayerEmail(String payerEmail) {
		this.payerEmail = payerEmail;
	}

	@Column(name = "type_pay", nullable = false, length = 50)
	public String getTypePay() {
		return this.typePay;
	}

	public void setTypePay(String typePay) {
		this.typePay = typePay;
	}

	@Column(name = "discount", nullable = false, precision = 22, scale = 0)
	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	@Column(name = "total_money", nullable = false, precision = 22, scale = 0)
	public double getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(double totalMoney) {
		this.totalMoney = totalMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
