package com.demo.models;
// Generated Jan 7, 2022, 7:06:18 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetailBill generated by hbm2java
 */
@Entity
@Table(name = "detail_bill", catalog = "booking_hotel")
public class DetailBill implements java.io.Serializable {

	private DetailBillId id;
	private Bill bill;

	public DetailBill() {
	}

	public DetailBill(DetailBillId id, Bill bill) {
		this.id = id;
		this.bill = bill;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idBill", column = @Column(name = "id_bill", nullable = false, length = 250)),
			@AttributeOverride(name = "idRoom", column = @Column(name = "id_room", nullable = false)),
			@AttributeOverride(name = "accountIdHotel", column = @Column(name = "account_id_hotel", nullable = false, length = 250)),
			@AttributeOverride(name = "accountIdCustomer", column = @Column(name = "account_id_customer", nullable = false, length = 250)),
			@AttributeOverride(name = "payerName", column = @Column(name = "payer_name", nullable = false, length = 250)),
			@AttributeOverride(name = "payerPhone", column = @Column(name = "payer_phone", nullable = false)),
			@AttributeOverride(name = "payerEmail", column = @Column(name = "payer_email", nullable = false, length = 250)),
			@AttributeOverride(name = "typePay", column = @Column(name = "type_pay", nullable = false, length = 50)),
			@AttributeOverride(name = "totalMoney", column = @Column(name = "total_money", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "created", column = @Column(name = "created", nullable = false, length = 10)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false)) })
	public DetailBillId getId() {
		return this.id;
	}

	public void setId(DetailBillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bill", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

}
