package com.demo.models;
// Generated Jan 13, 2022, 7:32:19 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuestRating generated by hbm2java
 */
@Entity
@Table(name = "guest_rating", catalog = "booking_hotel")
public class GuestRating implements java.io.Serializable {

	private String idRating;
	private Account account;
	private double avgScore;
	private String message;
	private Date created;
	private String accountIdHotel;
	private boolean status;

	public GuestRating() {
	}

	public GuestRating(String idRating, Account account, double avgScore, String message, Date created,
			String accountIdHotel, boolean status) {
		this.idRating = idRating;
		this.account = account;
		this.avgScore = avgScore;
		this.message = message;
		this.created = created;
		this.accountIdHotel = accountIdHotel;
		this.status = status;
	}

	@Id

	@Column(name = "id_rating", unique = true, nullable = false, length = 250)
	public String getIdRating() {
		return this.idRating;
	}

	public void setIdRating(String idRating) {
		this.idRating = idRating;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id_customer", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "avg_score", nullable = false, precision = 22, scale = 0)
	public double getAvgScore() {
		return this.avgScore;
	}

	public void setAvgScore(double avgScore) {
		this.avgScore = avgScore;
	}

	@Column(name = "message", nullable = false, length = 16777215)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "account_id_hotel", nullable = false, length = 250)
	public String getAccountIdHotel() {
		return this.accountIdHotel;
	}

	public void setAccountIdHotel(String accountIdHotel) {
		this.accountIdHotel = accountIdHotel;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
