package com.demo.models;
// Generated Jan 11, 2022, 6:39:55 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Highlight generated by hbm2java
 */
@Entity
@Table(name = "highlight", catalog = "booking_hotel")
public class Highlight implements java.io.Serializable {

	private Integer idHighlight;
	private String nameHighlight;

	public Highlight() {
	}

	public Highlight(String nameHighlight) {
		this.nameHighlight = nameHighlight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_highlight", unique = true, nullable = false)
	public Integer getIdHighlight() {
		return this.idHighlight;
	}

	public void setIdHighlight(Integer idHighlight) {
		this.idHighlight = idHighlight;
	}

	@Column(name = "name_highlight", nullable = false, length = 250)
	public String getNameHighlight() {
		return this.nameHighlight;
	}

	public void setNameHighlight(String nameHighlight) {
		this.nameHighlight = nameHighlight;
	}

}
