package com.demo.models;
// Generated Jan 5, 2022, 9:32:17 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * HighlightRoom generated by hbm2java
 */
@Entity
@Table(name = "highlight_room", catalog = "booking_hotel")
public class HighlightRoom implements java.io.Serializable {

	private int idRoom;
	private InfoRoom infoRoom;
	private String highlight;

	public HighlightRoom() {
	}

	public HighlightRoom(InfoRoom infoRoom, String highlight) {
		this.infoRoom = infoRoom;
		this.highlight = highlight;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "infoRoom"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idRoom", unique = true, nullable = false)
	public int getIdRoom() {
		return this.idRoom;
	}

	public void setIdRoom(int idRoom) {
		this.idRoom = idRoom;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public InfoRoom getInfoRoom() {
		return this.infoRoom;
	}

	public void setInfoRoom(InfoRoom infoRoom) {
		this.infoRoom = infoRoom;
	}

	@Column(name = "highlight", nullable = false, length = 1000)
	public String getHighlight() {
		return this.highlight;
	}

	public void setHighlight(String highlight) {
		this.highlight = highlight;
	}

}
