package com.demo.models;
// Generated Jan 5, 2022, 9:32:17 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ImageRoom generated by hbm2java
 */
@Entity
@Table(name = "image_room", catalog = "booking_hotel")
public class ImageRoom implements java.io.Serializable {

	private int idRoom;
	private InfoRoom infoRoom;
	private String image;

	public ImageRoom() {
	}

	public ImageRoom(InfoRoom infoRoom, String image) {
		this.infoRoom = infoRoom;
		this.image = image;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "infoRoom"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idroom", unique = true, nullable = false)
	public int getIdRoom() {
		return this.idRoom;
	}

	public void setIdRoom(int idRoom) {
		this.idRoom = idRoom;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public InfoRoom getInfoRoom() {
		return this.infoRoom;
	}

	public void setInfoRoom(InfoRoom infoRoom) {
		this.infoRoom = infoRoom;
	}

	@Column(name = "image", nullable = false, length = 65535)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
