package com.demo.models;
// Generated Jan 7, 2022, 7:06:18 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoRoom generated by hbm2java
 */
@Entity
@Table(name = "info_room", catalog = "booking_hotel")
public class InfoRoom implements java.io.Serializable {

	private Integer idRoom;
	private Account account;
	private Date checkIn;
	private Date checkOut;
	private int guestChildren;
	private int guestAdult;
	private String description;
	private String roomCategory;
	private int quantityRoom;
	private double price;
	private double salePrice;
	private String locationDetail;
	private String imgRoom;
	private Date created;
	private boolean status;

	public InfoRoom() {
	}

	public InfoRoom(Account account, Date checkIn, Date checkOut, int guestChildren, int guestAdult, String description,
			String roomCategory, int quantityRoom, double price, double salePrice, String locationDetail,
			String imgRoom, Date created, boolean status) {
		this.account = account;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.guestChildren = guestChildren;
		this.guestAdult = guestAdult;
		this.description = description;
		this.roomCategory = roomCategory;
		this.quantityRoom = quantityRoom;
		this.price = price;
		this.salePrice = salePrice;
		this.locationDetail = locationDetail;
		this.imgRoom = imgRoom;
		this.created = created;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_room", unique = true, nullable = false)
	public Integer getIdRoom() {
		return this.idRoom;
	}

	public void setIdRoom(Integer idRoom) {
		this.idRoom = idRoom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_acc", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_in", nullable = false, length = 10)
	public Date getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out", nullable = false, length = 10)
	public Date getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "guest_children", nullable = false)
	public int getGuestChildren() {
		return this.guestChildren;
	}

	public void setGuestChildren(int guestChildren) {
		this.guestChildren = guestChildren;
	}

	@Column(name = "guest_adult", nullable = false)
	public int getGuestAdult() {
		return this.guestAdult;
	}

	public void setGuestAdult(int guestAdult) {
		this.guestAdult = guestAdult;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "room_category", nullable = false, length = 50)
	public String getRoomCategory() {
		return this.roomCategory;
	}

	public void setRoomCategory(String roomCategory) {
		this.roomCategory = roomCategory;
	}

	@Column(name = "quantity_room", nullable = false)
	public int getQuantityRoom() {
		return this.quantityRoom;
	}

	public void setQuantityRoom(int quantityRoom) {
		this.quantityRoom = quantityRoom;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "sale_price", nullable = false, precision = 22, scale = 0)
	public double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(double salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "location_detail", nullable = false, length = 250)
	public String getLocationDetail() {
		return this.locationDetail;
	}

	public void setLocationDetail(String locationDetail) {
		this.locationDetail = locationDetail;
	}

	@Column(name = "img_room", nullable = false, length = 65535)
	public String getImgRoom() {
		return this.imgRoom;
	}

	public void setImgRoom(String imgRoom) {
		this.imgRoom = imgRoom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
