package com.demo.models;
// Generated Jan 15, 2022, 10:40:43 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * InfoRoom generated by hbm2java
 */
@Entity
@Table(name = "info_room", catalog = "booking_hotel")
public class InfoRoom implements java.io.Serializable {

	private Integer idRoom;
	private Account account;
	
	
	@JsonFormat(pattern = "MM/dd/yyyy")
	@Temporal(TemporalType.DATE)
	private Date checkIn;
	
	
	@JsonFormat(pattern = "MM/dd/yyyy")
	@Temporal(TemporalType.DATE)
	private Date checkOut;
	
	
	private int guestChildren;
	private int guestAdult;
	private String description;
	private String roomCategory;
	private double price;
	private double salePrice;
	private double total;
	private String highlightRoom;
	private String imgRoom;
	private String extraImg1;
	private String extraImg2;
	private String extraImg3;
	
	@JsonFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	private Date created;
	private boolean status;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public InfoRoom() {
	}

	public InfoRoom(Account account, Date checkIn, Date checkOut, int guestChildren, int guestAdult, String description,
			String roomCategory, double price, double salePrice, double total, String highlightRoom, String imgRoom,
			String extraImg1, String extraImg2, String extraImg3, Date created, boolean status) {
		this.account = account;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.guestChildren = guestChildren;
		this.guestAdult = guestAdult;
		this.description = description;
		this.roomCategory = roomCategory;
		this.price = price;
		this.salePrice = salePrice;
		this.total = total;
		this.highlightRoom = highlightRoom;
		this.imgRoom = imgRoom;
		this.extraImg1 = extraImg1;
		this.extraImg2 = extraImg2;
		this.extraImg3 = extraImg3;
		this.created = created;
		this.status = status;
	}

	public InfoRoom(Account account, Date checkIn, Date checkOut, int guestChildren, int guestAdult, String description,
			String roomCategory, double price, double salePrice, double total, String highlightRoom, String imgRoom,
			String extraImg1, String extraImg2, String extraImg3, Date created, boolean status,
			Set<Reservation> reservations) {
		this.account = account;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.guestChildren = guestChildren;
		this.guestAdult = guestAdult;
		this.description = description;
		this.roomCategory = roomCategory;
		this.price = price;
		this.salePrice = salePrice;
		this.total = total;
		this.highlightRoom = highlightRoom;
		this.imgRoom = imgRoom;
		this.extraImg1 = extraImg1;
		this.extraImg2 = extraImg2;
		this.extraImg3 = extraImg3;
		this.created = created;
		this.status = status;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_room", unique = true, nullable = false)
	public Integer getIdRoom() {
		return this.idRoom;
	}

	public void setIdRoom(Integer idRoom) {
		this.idRoom = idRoom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_acc", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_in", nullable = false, length = 10)
	public Date getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out", nullable = false, length = 10)
	public Date getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "guest_children", nullable = false)
	public int getGuestChildren() {
		return this.guestChildren;
	}

	public void setGuestChildren(int guestChildren) {
		this.guestChildren = guestChildren;
	}

	@Column(name = "guest_adult", nullable = false)
	public int getGuestAdult() {
		return this.guestAdult;
	}

	public void setGuestAdult(int guestAdult) {
		this.guestAdult = guestAdult;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "room_category", nullable = false, length = 50)
	public String getRoomCategory() {
		return this.roomCategory;
	}

	public void setRoomCategory(String roomCategory) {
		this.roomCategory = roomCategory;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "sale_price", nullable = false, precision = 22, scale = 0)
	public double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(double salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@Column(name = "highlight_room", nullable = false, length = 65535)
	public String getHighlightRoom() {
		return this.highlightRoom;
	}

	public void setHighlightRoom(String highlightRoom) {
		this.highlightRoom = highlightRoom;
	}

	@Column(name = "img_room", nullable = false, length = 65535)
	public String getImgRoom() {
		return this.imgRoom;
	}

	public void setImgRoom(String imgRoom) {
		this.imgRoom = imgRoom;
	}

	@Column(name = "extra_Img1", nullable = false, length = 65535)
	public String getExtraImg1() {
		return this.extraImg1;
	}

	public void setExtraImg1(String extraImg1) {
		this.extraImg1 = extraImg1;
	}

	@Column(name = "extra_Img2", nullable = false, length = 65535)
	public String getExtraImg2() {
		return this.extraImg2;
	}

	public void setExtraImg2(String extraImg2) {
		this.extraImg2 = extraImg2;
	}

	@Column(name = "extra_Img3", nullable = false, length = 65535)
	public String getExtraImg3() {
		return this.extraImg3;
	}

	public void setExtraImg3(String extraImg3) {
		this.extraImg3 = extraImg3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infoRoom")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
