package com.demo.models;
// Generated Jan 16, 2022, 2:09:42 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "booking_hotel")
public class Reservation implements java.io.Serializable {

	private Integer idReservation;
	private InfoRoom infoRoom;
	private String customerId;
	private Date checkIn;
	private Date checkOut;
	private String name;
	private String email;
	private int phone;
	private Date created;
	private Set<DetailBill> detailBills = new HashSet<DetailBill>(0);

	public Reservation() {
	}

	public Reservation(InfoRoom infoRoom, String customerId, Date checkIn, Date checkOut, String name, String email,
			int phone, Date created) {
		this.infoRoom = infoRoom;
		this.customerId = customerId;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.created = created;
	}

	public Reservation(InfoRoom infoRoom, String customerId, Date checkIn, Date checkOut, String name, String email,
			int phone, Date created, Set<DetailBill> detailBills) {
		this.infoRoom = infoRoom;
		this.customerId = customerId;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.created = created;
		this.detailBills = detailBills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_reservation", unique = true, nullable = false)
	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public InfoRoom getInfoRoom() {
		return this.infoRoom;
	}

	public void setInfoRoom(InfoRoom infoRoom) {
		this.infoRoom = infoRoom;
	}

	@Column(name = "customer_id", nullable = false, length = 250)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_in", nullable = false, length = 10)
	public Date getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out", nullable = false, length = 10)
	public Date getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservation")
	public Set<DetailBill> getDetailBills() {
		return this.detailBills;
	}

	public void setDetailBills(Set<DetailBill> detailBills) {
		this.detailBills = detailBills;
	}

}
