package com.demo.models;
// Generated Jan 18, 2022, 2:01:32 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReservationCancel generated by hbm2java
 */
@Entity
@Table(name = "reservation_cancel", catalog = "booking_hotel")
public class ReservationCancel implements java.io.Serializable {

	private Integer idCancel;
	private Reservation reservation;
	private String reason;

	public ReservationCancel() {
	}

	public ReservationCancel(Reservation reservation, String reason) {
		this.reservation = reservation;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cancel", unique = true, nullable = false)
	public Integer getIdCancel() {
		return this.idCancel;
	}

	public void setIdCancel(Integer idCancel) {
		this.idCancel = idCancel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reservation", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@Column(name = "reason", nullable = false, length = 250)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
