package com.demo.models;
// Generated Jan 21, 2022, 12:57:47 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReservationCancel generated by hbm2java
 */
@Entity
@Table(name = "reservation_cancel", catalog = "booking_hotel")
public class ReservationCancel implements java.io.Serializable {

	private Integer idCancel;
	private Reservation reservation;
	private String reason;
	private String cancelledBy;
	private Date created;

	public ReservationCancel() {
	}

	public ReservationCancel(Reservation reservation, String reason, String cancelledBy, Date created) {
		this.reservation = reservation;
		this.reason = reason;
		this.cancelledBy = cancelledBy;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cancel", unique = true, nullable = false)
	public Integer getIdCancel() {
		return this.idCancel;
	}

	public void setIdCancel(Integer idCancel) {
		this.idCancel = idCancel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reservation", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@Column(name = "reason", nullable = false, length = 250)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "cancelled_by", nullable = false, length = 259)
	public String getCancelledBy() {
		return this.cancelledBy;
	}

	public void setCancelledBy(String cancelledBy) {
		this.cancelledBy = cancelledBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
